# .github/workflows/auto-sync-fork.yml
name: Auto Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Sync Fork
        uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: luxysiv
          base: main
          head: main
