name: Auto Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  workflows: write  # Add this permission

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "luxysiv/Cloudflare-Gateway-Pihole"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
